### ISSUE TITLE
Error: Cannot find preprocess script. (For sass in my case)

### ISSUE THREAD

**Issue by willdembinski** [michalkvasnicak/babel-plugin-css-modules-transform#35]
Have this configuration:
```
{
  "presets": ["es2015","stage-2","react"],
  "plugins": [
  "babel-plugin-webpack-alias",
    ["transform-object-rest-spread", { "useBuiltIns": true }],
    ["css-modules-transform",{
        "generateScopedName": "[name]__[local]___[hash:base64:5]",
        "preprocessCss": "./utils/sass_preprocess_tool.js",
        "extensions": [".css", ".scss"],
    }]
  ]
}
```

Using the exact script from the READ.me
```
// ./path/to/module-exporting-a-function.js
var sass = require('node-sass');
var path = require('path');

module.exports = function processSass(data, filename) {
    var result;
    result = sass.renderSync({
        data: data,
        file: filename
    }).css;
    return result.toString('utf8');
};
```

When using a relative file path get:
```
/home/pil0t/Projects/powr_x/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

Error: /home/pil0t/Projects/powr_x/src/api/server.js: Cannot find module './utils/sass_preprocess_tool.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireLocalFileOrNodeModule (/home/pil0t/Projects/powr_x/node_modules/babel-plugin-css-modules-transform/build/utils/requireLocalFileOrNodeModule.js:24:16)
```
When using absolute file path, get:
```
/home/pil0t/Projects/powr_x/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:578
        throw err;
        ^

Error: /home/pil0t/Projects/powr_x/utils/sass_preprocess_tool.js: Configuration file for 'preprocessCss' is not exporting a function
    at Object.preprocessCss (/home/pil0t/Projects/powr_x/node_modules/babel-plugin-css-modules-transform/build/options_resolvers/preprocessCss.js:25:15)
    at /home/pil0t/Projects/powr_x/node_modules/babel-plugin-css-modules-transform/build/index.js:131:66
    at Array.forEach (native)
```

**Comment by willdembinski** [comment]
Ultimately, the absolute file path at least resulting in a file being found is one thing.

But the fact that it doesn't accept the module is concerning.  Its entering as a blank object.  Indicative of a circular dependency, but there definitely isnt one :sad:

**Comment by michalkvasnicak** [comment]
I am sorry, I will take a look sometime in March, I don't have free time in February. I am moving to the other side of the country and I have to do a lot of stuff.

Could you provide a minimal repository where I can get this error?

Is this still with `babel-node` or this is happening for babel compilation using `babel` ?

**Comment by willdembinski** [comment]
`babel-node` :)  I could take a peak and suggest a PR if it would make your life easier?  Good luck on the move bro - I hope its not too stressful. :] Thanks for the help a la community!

**Comment by joaocrq** [comment]
Hello! Is there any news on this yet? Thanks!

**Comment by wi-ski** [comment]
I ended up patching - poorly - you check it out here: https://github.com/wi-ski/terriblepatchforcssmodules

I do not recommend using this at all.  However - it might point you in the right direction.

**Comment by michalkvasnicak** [comment]
@wi-ski I found that it was caused by `"babel-plugin-webpack-alias"`. I was refactoring code when I've got an error that `webpack.config.js` or `webpack.babel.config.js` are missing.

See screenshot

![image](https://cloud.githubusercontent.com/assets/174716/23822822/06fa58bc-0655-11e7-84c0-fd44c55ee092.png)

This caused node.js to throw an error as it was a circular dependency. 

I was trying your config. If you remove `babel-plugin-webpack-alias` everything should be fine. Could you reproduce this scenario please?

**Comment by michalkvasnicak** [comment]
@joaocrq Could you share your configuration or a minimum project to reproduce error?

**Comment by michalkvasnicak** [comment]
@wi-ski I created `webpack.config.js` in my `test_case` project with following contents:

```js
module.exports = {
    resolve: {
        alias: {
        }
    }
};
```

And plugin works without any problems with `babel-node`.

**Comment by michalkvasnicak** [comment]
@wi-ski ok previous comment is not true. It compiles but css is not written so I think that something swallows an error.

**Comment by michalkvasnicak** [comment]
@wi-ski could you try `next` version please?

**Comment by wi-ski** [comment]
@michalkvasnicak - Yea totally.  I cant do it yet.  But I haven't forgotten. Apologies for the delay.
