### ISSUE TITLE
Sometimes crashes

### ISSUE THREAD

**Issue by petermikitsh** [michalkvasnicak/babel-plugin-css-modules-transform#55]
Changing nothing, sometimes this transform causes an exception to be thrown.

Successful run:

```
$ npm run build:html

> NODE_ENV=production node build.js

(node:26056) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

Failure:

```
$ npm run build:html

> NODE_ENV=production node build.js

/Users/.../Paper.css:1
(function (exports, require, module, __filename, __dirname) { .root {
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
```

**Comment by petermikitsh** [comment]
I've observed if I edit my .babelrc file, e.g., change:

```
generateScopedName: "[name]__[local]___[hash:base64:5]"
```

to

```
generateScopedName: "[name]__[local]___[hash:base64:6]"
```

The first run will succeed, but all subsequent runs will fail.

**Comment by petermikitsh** [comment]
My build script uses `babel-register`.

Changing this:

```
require('babel-register');
```

to this:

```
require('babel-register')({cache: false});
```

Solves my problem. 🤔

**Comment by michalkvasnicak** [comment]
Maybe if you clean up a babel cache it will solve the problem too. Probably it is somehow caching the code compiled using incorrect settings.
