### ISSUE TITLE
Cannot read property 'keepImport' of undefined

### ISSUE THREAD

**Issue by pixelass** [michalkvasnicak/babel-plugin-css-modules-transform#71]
happens when:
```js
"plugins": ["css-modules-transform"]
```

vs. 

```js
"plugins": [
    ["css-modules-transform", {
      "keepImport": false
    }]
  ]
```

```shell
TypeError: src/button/index.js: Cannot read property 'keepImport' of undefined
    at PluginPass.ImportDefaultSpecifier (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-plugin-css-modules-transform/build/index.js:194:43)
    at newFn (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/greada/Documents/workspace/s2/s2-component-library/node_modules/babel-traverse/lib/path/context.js:115:19)
```

**Comment by michalkvasnicak** [comment]
What version of `babel` are you using? This is strange, because there is a test for this option and it's passing.

**Comment by pixelass** [comment]
```json
{
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-plugin-css-modules-transform": "^1.3.0"
}
```

**Comment by pixelass** [comment]
I am also using env and react as presets

```json
{
  "presets": ["react", ["env", {
    "targets": {
      "browsers": ["last 2 versions"]
    }
  }]]
}
```

**Comment by michalkvasnicak** [comment]
Yes I found a bug, give me a moment.

**Comment by michalkvasnicak** [comment]
Please try 1.3.1.

**Comment by pixelass** [comment]
Success 👍

Works like a charm. Thx for the great work.

**Comment by michalkvasnicak** [comment]
You are welcome 🙂
